version: '3.8'
services:
  pagamentos-api:
    build: .
    container_name: pagamentos-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./data:/data
